server.port=8082
logging.level.org.springframework.web=DEBUG

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_crm?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
